# Generated by Django 3.1.7 on 2021-03-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('user_type', models.IntegerField()),
                ('login_state', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=32)),
                ('teacher_name', models.CharField(max_length=32)),
                ('author_name', models.CharField(max_length=32)),
                ('content_1', models.IntegerField()),
                ('content_2', models.IntegerField()),
                ('content_3', models.IntegerField()),
                ('content_4', models.IntegerField()),
                ('content_5', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=32)),
                ('teacher_name', models.CharField(max_length=32)),
            ],
            options={
                'unique_together': {('course_name', 'teacher_name')},
            },
        ),
    ]
