# Generated by Django 3.1.7 on 2021-03-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='login_state',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='choicecomment',
            name='content_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='choicecomment',
            name='content_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='choicecomment',
            name='content_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='choicecomment',
            name='content_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='choicecomment',
            name='content_5',
            field=models.IntegerField(default=0),
        ),
    ]
