# Generated by Django 3.1.7 on 2021-03-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210323_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=32)),
                ('teacher_name', models.CharField(max_length=32)),
                ('author_name', models.CharField(max_length=32)),
                ('content', models.CharField(max_length=256)),
            ],
        ),
    ]
